//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Users
    {
        public TT_Users()
        {
            this.TT_Customers = new HashSet<TT_Customers>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<TT_Customers> TT_Customers { get; set; }
    }
}
